apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-chomper
spec:
  selector:
    matchLabels:
      run: memory-chomper
  replicas: 3
  template:
    metadata:
      labels:
        run: memory-chomper
    spec:
      containers:
      - name: memory-chomper
        image: gcr.io/alexmattson-scratch/github.com/theemadnes/k8s-memory-chomper@sha256:132fbc1f9d6df7c50c8fd1be31cf1c264db6faa029024c41da12924cfa088344
        #command: ["app.py"]
        #args: ["--megabytes 1000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1200Mi"
            cpu: "2000m"