apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-chomper
spec:
  selector:
    matchLabels:
      run: memory-chomper
  replicas: 20
  template:
    metadata:
      labels:
        run: memory-chomper
    spec:
      containers:
      - name: memory-chomper
        image: gcr.io/alexmattson-scratch/github.com/theemadnes/k8s-memory-chomper@sha256:1d029e9dbe0d433729aa5fc93afe7127368680ae3781c00d5b4edf50f7284a14
        #command: ["/app/app.py"]
        args: ["app.py", "--megabytes", "4000", "--delay", "10"]
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "2000m"