apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-chomper
spec:
  selector:
    matchLabels:
      run: memory-chomper
  replicas: 3
  template:
    metadata:
      labels:
        run: memory-chomper
    spec:
      containers:
      - name: memory-chomper
        image: gcr.io/alexmattson-scratch/github.com/theemadnes/k8s-memory-chomper@sha256:da31be61b9e3a542a152ccb25d84a0f52a7897104c14dfb6fe41f0f847eb9186
        #command: ["/app/app.py"]
        args: ["app.py", "--megabytes", "1000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1200Mi"
            cpu: "2000m"