apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-chomper
spec:
  selector:
    matchLabels:
      run: memory-chomper
  replicas: 50
  template:
    metadata:
      labels:
        run: memory-chomper
    spec:
      containers:
      - name: memory-chomper
        image: gcr.io/alexmattson-scratch/github.com/theemadnes/k8s-memory-chomper@sha256:31435f0bc894ec1310a68e942573b3ab1a05b0ed021e0b4b1f2b438ea2ad49a4
        #command: ["/app/app.py"]
        args: ["app.py", "--megabytes", "1000"]
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "2000m"