apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-chomper
spec:
  selector:
    matchLabels:
      run: memory-chomper
  replicas: 3
  template:
    metadata:
      labels:
        run: memory-chomper
    spec:
      containers:
      - name: memory-chomper
        image: gcr.io/alexmattson-scratch/github.com/theemadnes/k8s-memory-chomper@sha256:9f2fc404eedb501aad9c02f211b6631c2052558bc9e6066547c35c63b4cc88b0
        #command: ["app.py"]
        #args: ["--megabytes 1000"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1200Mi"
            cpu: "2000m"